# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        Latexify.jl
repo_url:         https://github.com/korsbo/Latexify.jl
site_description: Documentation for Latexify.jl
site_author:      Niklas Korsbo

theme: readthedocs
#theme: biojulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite

docs_dir: 'build'

pages:
- Introduction: index.md
- Tutorial:
  - Title 1: tutorials/latexify.md
  - Title 2: tutorials/latexarray.md
- Another Section:
  - Title 1: functions/latexify.md
  - Title 2: functions/latexarray.md
